#!/usr/bin/env python3

from email.mime.multipart import MIMEMultipart
from email.utils import formatdate
from subprocess import Popen, PIPE

import unittest
import sys

def createBasicMessage(frm = None, to = None, subject = None):
    msg = MIMEMultipart()

    if(subject):
        msg['Subject'] = subject

    if(frm):
        msg['From'] = frm

    if(to):
        msg['To'] = to

    msg['Date'] = formatdate()
    return msg

def invokeEmail2PDF(message):
    textMessage = message.as_string()
    p = Popen(['./email2pdf', '-d', '/tmp'], stdin=PIPE)
    output = p.communicate(input = bytes(textMessage, 'UTF-8'))
    p.wait()
    return p.returncode

class TestText(unittest.TestCase):
    def test_basic(self):
        msg = createBasicMessage("From", "To", "Subject")
        self.assertEqual(invokeEmail2PDF(msg), 0)

    def test_nosubject(self):
        msg = createBasicMessage("From", "To")
        self.assertEqual(invokeEmail2PDF(msg), 0)

if __name__ == '__main__':
    unittest.main()
