#!/usr/bin/env python

from __future__ import print_function

from datetime import datetime
from subprocess import Popen, PIPE
import email
import getopt
import os
import os.path
import sys

HEADERS = ('Subject', 'From', 'To', 'Date')

def main(argv):
    inputFile = ''
    outputFileName = ''
    try:
        opts, args = getopt.getopt(argv, "i:o:d:t", ["inputFile=","outputFile=", "outputDirectory=", "timedOutputFile"])
    except getopt.GetoptError:
        print('email2pdf.py -i <inputFile> -o <outputFile> [-t]')
        sys.exit(2)
    for opt, arg in opts:
        if opt in ("-i", "--inputFile"):
            inputFile = arg
        elif opt in ("-o", "--outputFile"):
            outputFileName = arg
        elif opt in ("-d", "--outputDirectory"):
            outputDirectory = arg
        elif opt in ("-t", "--timedOutputFile"):
            outputFileName = outputDirectory.rstrip("/") + "/" + datetime.now().strftime("%Y-%m-%dT%H-%M-%S") + ".pdf"

    if os.path.isfile(outputFileName):
        print("ERROR: Output file " + outputFileName + " already exists. Aborting.", file=sys.stderr)

    if inputFile.strip() == "-":
        data = ""
        for line in sys.stdin:
            data += line
    else:
        with open(inputFile, "r") as inputHandle:
            data = inputHandle.read()

    myEmail = email.message_from_string(data)

    headerInfo = ''
    for header in HEADERS:
        headerInfo = headerInfo + '<b>' + header + '</b>: ' + myEmail[header] + '<br/>'

    headerInfo = headerInfo + '<br/>'

    payload = find_depth_first(myEmail, "application/pdf")
    if payload == None:
        payload = find_depth_first(myEmail, "text/html")
        if payload == None:
            payload = find_depth_first(myEmail, "text/plain")
            if payload == None:
                print("ERROR: Cannot find an appropriate payload in email.", file=sys.stderr)
            else:
                payload = "<html><body><pre>\n" + payload + "\n</pre></body></html>"

        payload = headerInfo + payload

        p = Popen(['wkhtmltopdf', '-q', '--load-error-handling', 'ignore', '--load-media-error-handling', 'ignore', '-', outputFileName], stdin=PIPE)
        output = p.communicate(input = payload)
    else:
        with open(outputFileName, 'wb') as outputFile:
            outputFile.write(payload)

def find_depth_first(message, content_type):
    if message.is_multipart():
        for part in message.get_payload():
            value = find_depth_first(part, content_type)
            if value != None:
                return value
    elif message.get_content_type() == content_type:
        return message.get_payload(decode = True)
    else:
        return None

if __name__ == "__main__":
   main(sys.argv[1:])
